apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitops-foundations
  namespace: argo-demo
  labels:
    app: gitops-foundations
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: gitopsfoundations.westus2.cloudapp.azure.com
      http:
        paths:
          - backend:
              serviceName: gitops-foundations-load-balancer
              servicePort: 8080
            path: /gitops-foundations-load-balancer(/|$)(.*)
