apiVersion: v1
kind: Service
metadata:
  name: gitops-foundations-load-balancer
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: gitopsfoundations
  namespace: argo-demo
spec:
  type: LoadBalancer
  selector:
    app: gitops-foundations 
  ports:
    - port: 80
      targetPort: 8080
